# Generated by Django 3.1.11 on 2021-05-14 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_pokemon_next_evolution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='next_evolution',
            new_name='prev_evolution',
        ),
    ]
